
services:
  backend:
    build: .
    working_dir: /app
    container_name: med_appointment_backend
    command: >
      sh -c "python manage.py flush --no-input &&
             python manage.py migrate &&
             python manage.py seed_test_doctor &&
             python manage.py collectstatic --no-input &&
             gunicorn med_appointment.wsgi:application --bind 0.0.0.0:8000 --workers 2"
    env_file:
      - ./.env
    dns:
      - 8.8.8.8
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    volumes:
      - static_volume:/app/staticfiles
    expose:
      - "8000"
    restart: always

  nginx:
    image: nginx:latest
    container_name: med_appointment_nginx
    ports:
      - "80:80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
    depends_on:
      - backend
    restart: always

volumes:
  static_volume: